name: schema-registry-ci
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-source:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install phars
        run: |
          make install-phars
      -
        name: Upload source directory
        uses: actions/upload-artifact@v4
        with:
          name: source
          include-hidden-files: true
          path: .
  php-xdebug-docker:
    needs:
      - build-source
    strategy:
      matrix:
        php:
          -
            version: '7.4'
            xdebug: '3.1.5'
          -
            version: '8.0'
            xdebug: '3.1.5'
          -
            version: '8.1'
            xdebug: '3.1.5'
          -
            version: '8.2'
            xdebug: '3.2.1'
    runs-on: ubuntu-22.04
    steps:
      -
        name: Download sources
        uses: actions/download-artifact@v4
        with:
          name: source
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: schema-registry-client:${{ matrix.php.version }}
          build-args: |
            PHP_VERSION=${{ matrix.php.version }}
            XDEBUG_VERSION=${{ matrix.php.xdebug }}
      -
        name: Inspect docker image
        run: |
          docker image inspect schema-registry-client:${{ matrix.php.version }}
      -
        name: Save docker image
        run: |
          docker save schema-registry-client:${{ matrix.php.version }} -o schema-registry-client-${{ matrix.php.version }}.tgz
      -
        name: Upload docker image
        uses: actions/upload-artifact@v4
        with:
          name: schema-registry-client-${{ matrix.php.version }}
          path: schema-registry-client-${{ matrix.php.version }}.tgz
  ci-checks:
    runs-on: ubuntu-22.04
    needs:
      - php-xdebug-docker
    strategy:
      matrix:
        php:
          -
            version: '7.4'
            composer: --prefer-lowest
          -
            version: '8.0'
            composer: --prefer-lowest
          -
            version: '8.1'
            composer: --prefer-lowest
          -
            version: '8.2'
            composer: --prefer-lowest
          -
            version: '7.4'
            composer: --prefer-stable
          -
            version: '8.0'
            composer: --prefer-stable
          -
            version: '8.1'
            composer: --prefer-stable
          -
            version: '8.2'
            composer: --prefer-stable
    steps:
      -
        name: Download sources
        uses: actions/download-artifact@v4
        with:
          name: source
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: schema-registry-client-${{ matrix.php.version }}
      -
        name: Load docker image
        run: |
          docker load -i schema-registry-client-${{ matrix.php.version }}.tgz
      -
        name: Install vendors
        run: |
          docker run -i --rm --net=host --sig-proxy=true --pid=host \
            -v "${GITHUB_WORKSPACE}":"${GITHUB_WORKSPACE}" -w "${GITHUB_WORKSPACE}" schema-registry-client:${{ matrix.php.version }} \
            composer update --no-interaction --no-scripts --no-ansi ${{ matrix.php.composer }}
      -
        name: Run PHPStan analysis
        if: ${{ matrix.php.version == '7.4' && matrix.php.composer == '--prefer-stable' }}
        run: |
          chmod a+x bin/phpstan.phar
          docker run -i --rm --net=host --sig-proxy=true --pid=host -m 4000M --entrypoint="php" \
            -v "${GITHUB_WORKSPACE}":"${GITHUB_WORKSPACE}" -w "${GITHUB_WORKSPACE}" schema-registry-client:${{ matrix.php.version }} \
            -d memory_limit=4G -d xdebug.mode=off bin/phpstan.phar analyse
      -
        name: Run CS Fixer
        if: ${{ matrix.php.version == '7.4' && matrix.php.composer == '--prefer-stable' }}
        run: |
          chmod a+x bin/php-cs-fixer.phar
          docker run -i --rm --net=host --sig-proxy=true --pid=host -m 1000M --entrypoint="php" \
            -v "${GITHUB_WORKSPACE}":"${GITHUB_WORKSPACE}" -w "${GITHUB_WORKSPACE}" schema-registry-client:${{ matrix.php.version }} \
            -d xdebug.mode=off -d xdebug.coverage_enable=0 bin/php-cs-fixer.phar fix --config=.php-cs-fixer.dist.php \
            --diff -v --dry-run --path-mode=intersection --allow-risky=yes \
            src test
      -
        name: Run PHPUnit
        if: ${{ !(matrix.php.version == '7.4' && matrix.php.composer == '--prefer-stable') }}
        run: |
          docker run -i --rm --net=host --sig-proxy=true --pid=host \
            -v "${GITHUB_WORKSPACE}":"${GITHUB_WORKSPACE}" -w "${GITHUB_WORKSPACE}" schema-registry-client:${{ matrix.php.version }} \
            vendor/bin/phpunit --exclude-group integration
      -
        name: Run PHPUnit with Coverage Report
        if: ${{ matrix.php.version == '7.4' && matrix.php.composer == '--prefer-stable' }}
        run: |
          mkdir -p build
          docker run -i --rm --net=host --sig-proxy=true --pid=host \
            -v "${GITHUB_WORKSPACE}":"${GITHUB_WORKSPACE}" -w "${GITHUB_WORKSPACE}" schema-registry-client:${{ matrix.php.version }} \
            -d xdebug.mode=coverage vendor/bin/phpunit --exclude-group integration --coverage-clover=build/coverage.clover --coverage-text
      - name: Publish code coverage
        if: ${{ matrix.php.version == '7.4' && matrix.php.composer == '--prefer-stable' && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CODE_CLIMATE_REPORTER_ID}}
        with:
          coverageLocations: |
            ${{github.workspace}}/build/coverage.clover:clover
  confluent-integration:
    runs-on: ubuntu-22.04
    needs:
      - php-xdebug-docker
    strategy:
      matrix:
        confluent:
          -
            version: latest
          -
            version: 4.1.4
          -
            version: 5.5.2
    steps:
      -
        name: Download sources
        uses: actions/download-artifact@v4
        with:
          name: source
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: schema-registry-client-7.4
      -
        name: Load docker image
        run: |
          docker load -i schema-registry-client-7.4.tgz
      -
        name: Install vendors
        run: |
          docker run -i --rm --net=host --sig-proxy=true --pid=host \
            -v "${GITHUB_WORKSPACE}":"${GITHUB_WORKSPACE}" -w "${GITHUB_WORKSPACE}" schema-registry-client:7.4 \
            composer update --no-interaction --no-scripts --no-ansi --prefer-stable
      -
        name: Run PHPUnit Integration
        env:
          CONFLUENT_VERSION: ${{ matrix.confluent.version }}
        run: |
          chmod a+x bin/wait-for-all.sh bin/wait-for-it.sh
          make platform
          docker run -i --rm --net=host --sig-proxy=true --pid=host \
            -e ENABLE_INTEGRATION_TEST=1 -e TEST_SCHEMA_REGISTRY_HOST=172.68.0.103 -e TEST_SCHEMA_REGISTRY_PORT=8081 \
            -v "${GITHUB_WORKSPACE}":"${GITHUB_WORKSPACE}" -w "${GITHUB_WORKSPACE}" schema-registry-client:7.4 \
            vendor/bin/phpunit --group integration
